import { useState, useEffect } from 'react';
import {
    Plus,
    Edit2,
    Layout,
    Search,
    Monitor,
    Smartphone
} from 'lucide-react';
import axios from 'axios';
import toast from 'react-hot-toast';
import EmailBuilder from './builder/EmailBuilder';

export default function EmailTemplateList() {
    const [templates, setTemplates] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [showBuilder, setShowBuilder] = useState(false);
    const [editingTemplate, setEditingTemplate] = useState<any>(null);

    useEffect(() => {
        fetchTemplates();
    }, []);

    const fetchTemplates = async () => {
        try {
            setLoading(true);
            const response = await axios.get('/api/email-marketing/templates');
            setTemplates(response.data);
        } catch (error) {
            toast.error('Erro ao carregar templates');
        } finally {
            setLoading(false);
        }
    };

    const handleCreate = () => {
        setEditingTemplate(null);
        setShowBuilder(true);
    };

    const handleEdit = (template: any) => {
        setEditingTemplate(template);
        setShowBuilder(true);
    };

    const handleSaveTemplate = async (blocks: any) => {
        try {
            const payload = {
                nome: editingTemplate?.nome || `Template ${new Date().toLocaleDateString()}`,
                assunto: editingTemplate?.assunto || 'Novo Assunto',
                dados_json: blocks,
                corpo_html: '<!-- Generated by Visual Builder -->'
            };

            if (editingTemplate) {
                await axios.put(`/api/email-marketing/templates/${editingTemplate.id}`, payload);
                toast.success('Template atualizado!');
            } else {
                await axios.post('/api/email-marketing/templates', payload);
                toast.success('Template criado!');
            }

            setShowBuilder(false);
            fetchTemplates();
        } catch (error) {
            toast.error('Erro ao salvar template');
        }
    };

    const filtered = templates.filter(t => t.nome.toLowerCase().includes(search.toLowerCase()));

    if (showBuilder) {
        return <EmailBuilder onSave={handleSaveTemplate} initialData={editingTemplate?.dados_json || []} />;
    }

    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div className="relative flex-1 max-w-md">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/20" />
                    <input
                        type="text"
                        placeholder="Pesquisar templates..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full bg-white/5 border border-white/10 rounded-xl py-2 pl-10 pr-4 text-sm text-white focus:border-purple-500 transition-all outline-none"
                    />
                </div>
                <button
                    onClick={handleCreate}
                    className="flex items-center gap-2 px-6 py-2 rounded-xl bg-purple-600 text-white font-bold hover:bg-purple-700 transition-all shadow-lg shadow-purple-500/20"
                >
                    <Plus className="w-4 h-4" />
                    <span>Criar Template</span>
                </button>
            </div>

            {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {[1, 2, 3].map(i => (
                        <div key={i} className="h-64 rounded-3xl bg-white/5 animate-pulse border border-white/10" />
                    ))}
                </div>
            ) : filtered.length === 0 ? (
                <div className="text-center py-20">
                    <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-4">
                        <Layout className="w-10 h-10 text-white/20" />
                    </div>
                    <h3 className="text-white font-bold text-xl">Nenhum template encontrado</h3>
                    <p className="text-white/40 mt-2">Comece criando seu primeiro design visual.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {filtered.map((template) => (
                        <div key={template.id} className="group relative bg-white/5 border border-white/10 rounded-3xl overflow-hidden hover:border-purple-500/50 transition-all flex flex-col">
                            <div className="aspect-[4/3] bg-gray-800 flex items-center justify-center relative overflow-hidden p-4">
                                <div className="w-full h-full bg-white rounded-lg shadow-2xl flex flex-col p-2 gap-1 overflow-hidden scale-90 group-hover:scale-100 transition-transform duration-500">
                                    <div className="h-4 w-1/2 bg-gray-100 rounded" />
                                    <div className="h-px w-full bg-gray-50 my-1" />
                                    <div className="h-32 w-full bg-gray-100 rounded" />
                                    <div className="flex gap-1 mt-auto">
                                        <div className="h-2 w-full bg-gray-50 rounded" />
                                        <div className="h-2 w-full bg-gray-50 rounded" />
                                    </div>
                                </div>
                                <div className="absolute inset-0 bg-black/60 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                                    <button onClick={() => handleEdit(template)} className="p-3 bg-white text-gray-900 rounded-full hover:scale-110 transition-all font-bold">
                                        <Edit2 className="w-5 h-5" />
                                    </button>
                                </div>
                            </div>

                            <div className="p-5 flex flex-col gap-1">
                                <div className="flex items-center justify-between">
                                    <h4 className="text-white font-bold truncate pr-4">{template.nome}</h4>
                                    <div className="flex items-center gap-1.5 opacity-40">
                                        <Monitor className="w-3 h-3" />
                                        <Smartphone className="w-3 h-3" />
                                    </div>
                                </div>
                                <p className="text-[10px] text-white/30 uppercase font-black tracking-widest">{template.assunto || 'Sem assunto'}</p>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}
